language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - travis_wait 30 npm install
  - psql -c 'create database teamwork;' -U postgres
  - travis_wait npm install
  - node database/init_db.js createAllTables
  - travis_wait 30 node database/init_data.js insertAllData
script:
  - npm test